name: 习讯云自动签到

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # 添加手动触发
    inputs:
      reason:
        description: '手动触发原因 (可选)'
        required: false
        default: '手动触发'

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: 签到日志
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ADDRESS: ${{ secrets.ADDRESS }}
          ADDRESS_NAME: ${{ secrets.ADDRESS_NAME }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          SCHOOL_ID: ${{ secrets.SCHOOL_ID }}
          EMAIL: ${{ secrets.EMAIL }}
          CODE: ${{ secrets.CODE }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          npm install
          node app.js
      - name: 打印触发原因 (可选)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Workflow was manually triggered. Reason: ${{ github.event.inputs.reason }}"
